### ISSUE TITLE
Implement plugin priority

### ISSUE THREAD

**Issue by gwmensink** [DerPopo/SurvivalKit#1]
The priority of a plugin is used to determine the execution order when handling events.
A plugin should be able to determine the plugin priority per event.
When handling an event, a plugin with the high priority should be called before plugins with the priority normal.
When two plugins have the same priority on an event, the order in which the plugins are loaded should be used to determine the execution order.

There is some work done on priority, but it needs to be finished.
Priority levels are defined in SurvivalKit.Events.Priority enumeration.

**Comment by DerPopo** [comment]
Implemented it.
