### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [DerPopo/SurvivalKit#3]
Hi there i did not know how else to contact you, im busy creating a server manager for 7DTD and im wondering can you help me with something?

**Comment by gwmensink** [comment]
Hello,

Interesting way of contacting people :).
May I suggest you join IRC? 
You should be able to meet one of us there.

Network: irc.gamesurge.net
Channel: #7daystodie
My username: GWM
@DerPopo username: DerPopo

In case you do not have an IRC client, you could use this web client:
http://mibbit.com/?channel=%237daystodie&server=irc.gamesurge.net
